Intersección de trayectorias.

Tres objetos se mueven de tal manera que sus trayectorias son:

$$2x-y+3z=24$$
$$2y-z=14$$
$$7x-5y=6$$

Encontrar su punto de interseccion:

In [14]:
import numpy as np


def gauss_eliminacion():
    print("Ingrese los coeficientes del sistema de ecuaciones:")
    n = 3
    a = []
    b = []

    for i in range(n):
        ecuacion = []
        print(f"Ecuación {i + 1}:")
        for j in range(n):
            coef = float(input(f"Coeficiente de la variable {chr(120 + j)}: "))
            ecuacion.append(coef)
        a.append(ecuacion)
        b.append(float(input("Término independiente: ")))

    a = np.array(a)
    b = np.array(b)

    print("\nMatriz inicial:")
    matriz_inicial = np.concatenate((a, b.reshape(-1, 1)), axis=1)
    print(matriz_inicial)

    for k in range(n - 1):
        for i in range(k + 1, n):
            if matriz_inicial[i, k] != 0.0:
                factor = matriz_inicial[i, k] / matriz_inicial[k, k]
                matriz_inicial[i] -= factor * matriz_inicial[k]

    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (matriz_inicial[i, -1] - np.dot(matriz_inicial[i, i + 1:n], x[i + 1:n])) / matriz_inicial[i, i]

    print("\nLa solucion es:")
    for i in range(n):
        print(f"{chr(120 + i)} = {x[i]:.2f}")

if __name__ == "__main__":
    gauss_eliminacion()

Ingrese los coeficientes del sistema de ecuaciones:
Ecuación 1:
Coeficiente de la variable x: 2
Coeficiente de la variable y: -1
Coeficiente de la variable z: 3
Término independiente: 24
Ecuación 2:
Coeficiente de la variable x: 0
Coeficiente de la variable y: 2
Coeficiente de la variable z: -1
Término independiente: 14
Ecuación 3:
Coeficiente de la variable x: 7
Coeficiente de la variable y: -5
Coeficiente de la variable z: 0
Término independiente: 6

Matriz inicial:
[[ 2. -1.  3. 24.]
 [ 0.  2. -1. 14.]
 [ 7. -5.  0.  6.]]

La solucion es:
x = 8.00
y = 10.00
z = 6.00


Carga de los quarks

Los protones y neutrones están formados cada uno por tres quarks. Los protones poseen dos quarks up (u) y un quark down (d), los neutrones poseen un quark up y dos quarks down. Si la carga de un protón es igual al positivo de la carga del electrón $(+e)$
y la carga de un neutrón es cero, determine las cargas de los quarks up y down. (Tip: suponga que $+e=1$.)


Primero proponemos un sistema de ecuaciones que me permita hallar la solucion:
$$2x+y=1$$
$$x+2y=0$$
Donde  
x: quarks up  
y: quarks down

In [19]:
import numpy as np


def gauss_eliminacion():
    print("Ingrese los coeficientes del sistema de ecuaciones:")
    n = int(input("Numero de variables:"))
    a = []
    b = []

    for i in range(n):
        ecuacion = []
        print(f"Ecuación {i + 1}:")
        for j in range(n):
            coef = float(input(f"Coeficiente de la variable {chr(120 + j)}: "))
            ecuacion.append(coef)
        a.append(ecuacion)
        b.append(float(input("Término independiente: ")))

    a = np.array(a)
    b = np.array(b)

    print("\nMatriz inicial:")
    matriz_inicial = np.concatenate((a, b.reshape(-1, 1)), axis=1)
    print(matriz_inicial)

    for k in range(n - 1):
        for i in range(k + 1, n):
            if matriz_inicial[i, k] != 0.0:
                factor = matriz_inicial[i, k] / matriz_inicial[k, k]
                matriz_inicial[i] -= factor * matriz_inicial[k]

    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (matriz_inicial[i, -1] - np.dot(matriz_inicial[i, i + 1:n], x[i + 1:n])) / matriz_inicial[i, i]

    print("\nLa solucion es:")
    for i in range(n):
        print(f"{chr(120 + i)} = {x[i]:.2f}")


if __name__ == "__main__":
    gauss_eliminacion()

Ingrese los coeficientes del sistema de ecuaciones:
Numero de variables:2
Ecuación 1:
Coeficiente de la variable x: 2
Coeficiente de la variable y: 1
Término independiente: 1
Ecuación 2:
Coeficiente de la variable x: 1
Coeficiente de la variable y: 2
Término independiente: 0

Matriz inicial:
[[2. 1. 1.]
 [1. 2. 0.]]

La solucion es:
x = 0.67
y = -0.33



Meteoros

El Centro de Investigación 1 examina la cantidad de meteoros que entran a la atmósfera. Con su equipo de recopilación de datos durante 8 horas captó 95kg de meteoros, por fuentes externas sabemos que fueron de 4 distintas masas (1kg, 5kg, 10kg y 20kg). La cantidad total de meteoros fue de 26. Otro centro de investigación captó que la cantidad de meteoros de 5kg es 4 veces la cantidad de meteoros de 10kg, y el número de meteoros de 1kg es 1 menos que el doble de la cantidad de meteoros de 5kg. Después use matrices para encontrar el número asociado a cada masa de meteoros.


Para resolver este problema proponemos el sistema de ecuaciones 
$$x+y+z+w=26$$
$$x+5y+10z+20w=95$$
$$y-4z=0$$
$$x-2y=−1$$

Donde  
x: Meteoros de 1kg.  
y: Meteoros de 5 kg.  
z: Meteoros de 10 kg.  
w: Meteoros de 20 kg.

In [20]:
import numpy as np


def gauss_eliminacion():
    print("Ingrese los coeficientes del sistema de ecuaciones:")
    n = int(input("Numero de variables:"))
    a = []
    b = []

    for i in range(n):
        ecuacion = []
        print(f"Ecuación {i + 1}:")
        for j in range(n):
            coef = float(input(f"Coeficiente de la variable X{j + 1}: "))
            ecuacion.append(coef)
        a.append(ecuacion)
        b.append(float(input("Término independiente: ")))

    a = np.array(a)
    b = np.array(b)

    print("\nMatriz inicial:")
    matriz_inicial = np.concatenate((a, b.reshape(-1, 1)), axis=1)
    print(matriz_inicial)

    for k in range(n - 1):
        for i in range(k + 1, n):
            if matriz_inicial[i, k] != 0.0:
                factor = matriz_inicial[i, k] / matriz_inicial[k, k]
                matriz_inicial[i] -= factor * matriz_inicial[k]

    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (matriz_inicial[i, -1] - np.dot(matriz_inicial[i, i + 1:n], x[i + 1:n])) / matriz_inicial[i, i]

    print("\nLa solucion es:")
    for i in range(n):
        print(f"X{i + 1} = {x[i]:.2f}")


if __name__ == "__main__":
    gauss_eliminacion()

Ingrese los coeficientes del sistema de ecuaciones:
Numero de variables:4
Ecuación 1:
Coeficiente de la variable X1: 1
Coeficiente de la variable X2: 1
Coeficiente de la variable X3: 1
Coeficiente de la variable X4: 1
Término independiente: 26
Ecuación 2:
Coeficiente de la variable X1: 1
Coeficiente de la variable X2: 5
Coeficiente de la variable X3: 10
Coeficiente de la variable X4: 20
Término independiente: 95
Ecuación 3:
Coeficiente de la variable X1: 0
Coeficiente de la variable X2: 1
Coeficiente de la variable X3: -4
Coeficiente de la variable X4: 0
Término independiente: 0
Ecuación 4:
Coeficiente de la variable X1: 1
Coeficiente de la variable X2: -2
Coeficiente de la variable X3: 0
Coeficiente de la variable X4: 0
Término independiente: -1

Matriz inicial:
[[ 1.  1.  1.  1. 26.]
 [ 1.  5. 10. 20. 95.]
 [ 0.  1. -4.  0.  0.]
 [ 1. -2.  0.  0. -1.]]

La solucion es:
X1 = 15.00
X2 = 8.00
X3 = 2.00
X4 = 1.00
